# Generated by Django 6.0.5 on 2026-05-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiApp", "0004_alter_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
